"""
Canonical data loading for the Dangerous Space Repositioning project.

Reuses the EXACT SAME causal tracking pipeline already established (and
already shipped/validated) by `pressing_structure` and `offside_break`:
`tactical_shared.tracking.build_quality_view` + `current_roles`. That
pipeline, unlike `analytics.position_fill.build_full_display_frame`,
NEVER interpolates a missing position and computes velocity from a
strictly backward-looking (causal) finite-difference / short least-
squares fit -- exactly the causality guarantee this project's own
brief requires ("historical frames are okay, future information is
not"). No new tracking/cleaning logic is invented here; this module
only assembles the already-existing causal view into the small
per-frame shape the rest of this project's analytics need.

Canonical data paths (real, on-disk, never regenerated by this
project):
  - outputs/tracking/testVideo1_120s/tracking.parquet   (raw tracking)
  - outputs/analytics/testVideo1_120s_v3/ball_trajectory.parquet
    (already-hardened ball trajectory, OBSERVED/PREDICTED/LOST intact)

Team convention for THIS project (matches the attached reference
mockup, not pressing_structure/offside_break's own green/gold
convention -- documented explicitly since it differs):
  team_id == 0  ->  "Team A" (blue in the dashboard)
  team_id == 1  ->  "Team B" (red in the dashboard)
"""
import bisect
import os
from collections import Counter
from dataclasses import dataclass, field

import numpy as np
import polars as pl

from tactical_shared.coordinates import DEFAULT_PITCH
from tactical_shared.tracking import build_quality_view, current_roles

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TRACKING_PARQUET = os.path.join(REPO_ROOT, "outputs/tracking/testVideo1_120s/tracking.parquet")
BALL_TRAJECTORY_PARQUET = os.path.join(REPO_ROOT, "outputs/analytics/testVideo1_120s_v3/ball_trajectory.parquet")
FPS = 30.0

TEAM_A = 0
TEAM_B = 1

# Tiered causal majority-vote windows for the attacking-team estimate
# (see `_compute_attacking_context`), tried smallest-first. 4.0s
# intentionally matches `tactical_shared.tracking.current_roles`'s own
# `historical_context_role` majority window (so the "current"/"4s"
# tiers agree with that already-established, already-accepted shared
# signal whenever it resolves) -- 12s/30s are THIS project's own
# extension, needed because real close-control (ball within 200cm of a
# player) observations are sparse and bursty on this clip (~4% of
# frames) with gaps up to 43.6s between them, so the shared 4s window
# alone leaves 53% of frames with no possession estimate at all (see
# docs/METHODOLOGY.md for the measurement).
ATTACKING_CONTEXT_WINDOWS_SEC = ((4.0, "4s_majority"), (12.0, "12s_majority"), (30.0, "30s_majority"))


def _compute_attacking_context(roles: list[dict], fps: float) -> list[dict]:
    """For every frame, the best available CAUSAL estimate of which team
    currently has the ball (and is therefore the CURRENT attacking
    team), built entirely from `tactical_shared.tracking.current_roles`'s
    own already-causal, already-backward-looking `carrier_team` field --
    never a future frame, never a fabricated carrier.

    Per frame, in priority order:
    1. This exact frame's real carrier (`carrier_team`), when the ball
       was genuinely within real close-control range this instant --
       `confidence="current"`.
    2. Otherwise, a majority vote of real close-control observations
       over an increasing trailing window (4s, then 12s, then 30s,
       stopping at the first window with a real, non-tied majority) --
       `confidence` names the window that resolved it. Every window is
       strictly backward-looking (only frames <= the queried frame are
       ever considered).
    3. If even a 30-second look-back finds no real observation (or an
       exact tie), the attacking team is genuinely unknown --
       `attacking_team=None, confidence="uncertain"`. NEVER fabricated.

    This tiered widening recovers a usable estimate for ~79% of frames
    on this clip (vs. ~47% using only the shared 4-second window) while
    remaining fully causal and honestly confidence-tiered -- see
    `docs/METHODOLOGY.md` for the full coverage measurement and
    `docs/METRIC_DEFINITIONS.md`/`HANDOFF.md`'s "Attacking-Phase
    Relevance Correction" section for how this feeds the dangerous-space
    selector."""
    event_frames = [r["frame"] for r in roles if r["carrier_team"] is not None]
    event_teams = [r["carrier_team"] for r in roles if r["carrier_team"] is not None]

    def majority_in_window(frame: int, window_sec: float):
        lo_frame = frame - window_sec * fps
        left = bisect.bisect_left(event_frames, lo_frame)
        right = bisect.bisect_right(event_frames, frame)
        teams = event_teams[left:right]
        if not teams:
            return None
        counts = Counter(teams)
        best = max(counts.values())
        winners = [t for t, c in counts.items() if c == best]
        return winners[0] if len(winners) == 1 else None

    out = []
    for f, role in enumerate(roles):
        if role["carrier_team"] is not None:
            out.append({"attacking_team": role["carrier_team"], "confidence": "current", "age_sec": 0.0})
            continue
        resolved = False
        for window_sec, label in ATTACKING_CONTEXT_WINDOWS_SEC:
            team = majority_in_window(f, window_sec)
            if team is not None:
                out.append({"attacking_team": team, "confidence": label, "age_sec": window_sec})
                resolved = True
                break
        if not resolved:
            out.append({"attacking_team": None, "confidence": "uncertain", "age_sec": None})
    return out


@dataclass
class MatchData:
    """Everything downstream analytics need, built once and reused.
    `players_by_frame[f]` is the list of raw `build_quality_view` row
    dicts for frame f (players + goalkeepers + referees, whatever was
    tracked that frame -- callers filter by `display_object_type`/
    `display_team_id`/`x_pitch is not None` themselves, same convention
    `pressing_structure`/`offside_break` already use)."""
    n_frames: int
    fps: float
    pitch: object
    players_by_frame: dict
    ball_by_frame: dict
    roles: list  # current_roles() output, index == frame
    attacking_context: list = field(default_factory=list)  # _compute_attacking_context() output, index == frame

    def attacking_team_at(self, frame: int) -> tuple[int | None, str]:
        """Best available CAUSAL (attacking_team, confidence) estimate
        for `frame` -- see `_compute_attacking_context`. Gracefully
        returns `(None, "uncertain")`, never raises, when this
        `MatchData` was built without possession data (e.g. a synthetic
        test fixture with `attacking_context=[]`) or for a frame beyond
        what was precomputed."""
        if frame < 0 or frame >= len(self.attacking_context):
            return None, "uncertain"
        ctx = self.attacking_context[frame]
        return ctx["attacking_team"], ctx["confidence"]

    def eligible_players(self, frame: int, team_id: int | None = None) -> list[dict]:
        """Real, currently-tracked outfield players + goalkeepers this
        frame (never fabricated). `team_id=None` returns both teams."""
        rows = self.players_by_frame.get(frame, [])
        out = []
        for r in rows:
            if r.get("x_pitch") is None or r.get("y_pitch") is None:
                continue
            if r["display_object_type"] not in ("player", "goalkeeper"):
                continue
            if team_id is not None and r.get("display_team_id") != team_id:
                continue
            out.append(r)
        return out

    def ball_at(self, frame: int) -> dict | None:
        b = self.ball_by_frame.get(frame)
        if b is None or not b.get("is_observed"):
            return None
        if b.get("x_pitch") is None or b.get("y_pitch") is None:
            return None
        return b


def load_match_data(tracking_path: str = TRACKING_PARQUET,
                     ball_path: str = BALL_TRAJECTORY_PARQUET,
                     fps: float = FPS, pitch=DEFAULT_PITCH) -> MatchData:
    """One real, causal, fully-materialized view of the canonical clip.
    Nothing here re-runs player detection/tracking/homography -- it only
    reads the already-computed parquet outputs and applies the
    already-existing causal quality/role/possession view on top."""
    tracking = pl.read_parquet(tracking_path)
    n_frames = int(tracking["frame"].max()) + 1
    quality = build_quality_view(tracking, fps=fps, pitch=pitch)

    players_by_frame: dict[int, list[dict]] = {}
    for r in quality.to_dicts():
        players_by_frame.setdefault(r["frame"], []).append(r)

    ball_df = pl.read_parquet(ball_path)
    ball_by_frame = {r["frame"]: r for r in ball_df.to_dicts()}

    roles = current_roles(players_by_frame, ball_by_frame, n_frames, fps=fps, pitch=pitch)
    attacking_context = _compute_attacking_context(roles, fps)

    return MatchData(n_frames=n_frames, fps=fps, pitch=pitch,
                      players_by_frame=players_by_frame, ball_by_frame=ball_by_frame, roles=roles,
                      attacking_context=attacking_context)


def player_dict(row: dict) -> dict:
    """Normalizes one `build_quality_view` row into the small dict shape
    every analytics module in this project expects: track_id, team_id,
    x_pitch, y_pitch, vx_cm_s, vy_cm_s, motion_valid. Missing/invalid
    motion is 0.0 with motion_valid=False -- NEVER a fabricated
    direction (same convention `pressure_field.py`/`pitch_control.py`
    already use elsewhere in this repo)."""
    return {
        "track_id": row["track_id"],
        "team_id": row.get("display_team_id"),
        "x_pitch": row["x_pitch"],
        "y_pitch": row["y_pitch"],
        "vx_cm_s": row.get("vx_cm_s") if row.get("motion_valid") else 0.0,
        "vy_cm_s": row.get("vy_cm_s") if row.get("motion_valid") else 0.0,
        "motion_valid": bool(row.get("motion_valid")),
    }


def frame_players(match: MatchData, frame: int) -> tuple[list[dict], list[dict]]:
    """(team_a_players, team_b_players) at `frame`, each a list of
    `player_dict()`-shaped dicts (goalkeepers included -- a keeper is a
    real spatial-control agent, same reasoning `analytics/voronoi.py`
    already documents for why it doesn't exclude them)."""
    team_a = [player_dict(r) for r in match.eligible_players(frame, TEAM_A)]
    team_b = [player_dict(r) for r in match.eligible_players(frame, TEAM_B)]
    return team_a, team_b


def outfield_only(players: list[dict], rows_by_track: dict) -> list[dict]:
    """Filters a player list down to outfield players only (excludes the
    goalkeeper) -- used by candidate-defender selection, where asking a
    goalkeeper to abandon the goal is never a realistic recommendation.
    `rows_by_track`: {track_id: raw build_quality_view row} for this
    frame, so the real `display_object_type` can be checked."""
    return [p for p in players if rows_by_track.get(p["track_id"], {}).get("display_object_type") == "player"]


def rows_by_track_id(match: MatchData, frame: int) -> dict:
    return {r["track_id"]: r for r in match.players_by_frame.get(frame, [])}
